"""
Django settings for shield_core project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(aou)x5ce+^uv)xh%i-j^u_yeca^5ws4g9w(+lq=$fxdlq68cb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ============================================================================
# 📦 APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',

    # Shield apps
    'users',
    'trips',
    'alerts',
    'faults',
    'audit',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # 🛡️ الـ Middleware المخصصة لطرد الأجهزة غير الموثوقة فوراً
    'shield_core.middleware.BlockUnverifiedSessionsMiddleware', 
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shield_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # تم التعديل هنا
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'shield_core.context_processors.role_base_template',
                'alerts.context_processors.notifications_badge',
                'users.context_processors.admin_pending_devices',
                'users.context_processors.admin_audit_badge',
                'faults.context_processors.faults_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'shield_core.wsgi.application'


# ============================================================================
# 🗄️ DATABASE CONFIGURATION (PostgreSQL)
# ============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shield_db',
        'USER': 'shield_user',
        'PASSWORD': 'shield2026',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ============================================================================
# 🔒 PASSWORD VALIDATION
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================================
# 🌐 INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ============================================================================
# 📁 STATIC & MEDIA FILES CONFIGURATION
# ============================================================================

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 🛠️ تأمين وإنشاء مجلد السجلات تلقائياً إذا كان مفقوداً
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)


# ============================================================================
# 🔐 AUTHENTICATION & USER MODEL CONFIGURATION
# ============================================================================

# تعريف الـ User Model المخصص للنظام
AUTH_USER_MODEL = 'users.User'

# روابط التوجيه الأساسية للمنظومة
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'trips:trip_list'  # التوجيه الافتراضي للرحلات بعد النجاح
LOGOUT_REDIRECT_URL = 'users:login'


# ============================================================================
# 📋 LOGIN ATTEMPT PROTECTION (حماية ضد التخمين Brute Force)
# ============================================================================

LOGIN_ATTEMPTS_LIMIT = 5
LOGIN_ATTEMPTS_TIMEOUT = 300  # مدة قفل الحساب: 5 دقائق


# ============================================================================
# 🍪 SESSION & SECURITY COOKIE SETTINGS (إدارة الجلسات والأمان)
# ============================================================================

# محرك تخزين الجلسات في قاعدة البيانات
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# اسم الكوكي الخاص بمنظومة شيلد
SESSION_COOKIE_NAME = 'shield_sessionid'

# مدة صلاحية الجلسة: 24 ساعة (يوم كامل بالثواني)
SESSION_COOKIE_AGE = 86400

# تحديث صلاحية الجلسة في قاعدة البيانات مع كل طلب لضمان دقة حقل التحقق والتوقيت
SESSION_SAVE_EVERY_REQUEST = True

# إغلاق الجلسة وحذفها فوراً عند إغلاق المتصفح (لحماية الأجهزة المشتركة)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# منع الوصول للـ Cookies عبر سكريبتات JavaScript (حماية من هجمات XSS)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# تحديد نطاق إرسال الكوكيز (منع هجمات CSRF)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# ⚠️ وضع التطوير المحلي (HTTP): تترك False هنا، وتُحول إلى True فقط عند استخدام HTTPS الفعلي
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# ============================================================================
# 🛡️ CSRF TRUSTED ORIGINS
# ============================================================================

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# ============================================================================
# 📝 LOGGING CONFIGURATION (سجلات الأحداث الأمنية والعمليات)
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/shield.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'users': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'trips': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
        },
    },
}
