# Generated by Django 6.0.6 on 2026-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('auditor', 'المراقب'), ('manager', 'المدير العام'), ('dispatcher', 'موظف المستودع'), ('agent', 'مندوب المحطة'), ('driver', 'سائق الشاحنة')], max_length=30, verbose_name='الدور'),
        ),
    ]
