# Generated by Django 6.0.6 on 2026-06-22 08:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint', models.CharField(db_index=True, help_text='معرّف فريد للمتصفح يتم توليده وتخزينه في Secure/HttpOnly Cookie', max_length=255, verbose_name='بصمة المتصفح')),
                ('user_agent', models.CharField(help_text='نوع ونسخة المتصفح ونظام التشغيل (User-Agent Header)', max_length=500, verbose_name='معلومات المتصفح')),
                ('is_trusted', models.BooleanField(default=True, help_text='هل تم التحقق من هذا المتصفح وتم اعتباره آمناً', verbose_name='متصفح موثق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ أول جلسة')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر استخدام')),
            ],
            options={
                'verbose_name': 'جلسة متصفح',
                'verbose_name_plural': 'جلسات المتصفحات',
                'db_table': 'user_browser_sessions',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='الاسم الكامل للمستخدم', max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='إذا كان True، يكون الحساب مقفولاً ولا يمكن الدخول', verbose_name='قفل الحساب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='عداد لعدد محاولات تسجيل الدخول الفاشلة المتتالية', verbose_name='عدد محاولات الدخول الفاشلة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='رقم الهاتف للتواصل (اختياري)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون من 9 إلى 15 رقماً', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('auditor', 'المراقب'), ('manager', 'المدير العام'), ('dispatcher', 'موظف المستودع'), ('agent', 'مندوب المحطة')], default='agent', help_text='تحديد الدور الوظيفي والصلاحيات المرتبطة به', max_length=30, verbose_name='الدور الوظيفي'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='shield_user_role_391546_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='shield_user_is_acti_4fb4b0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_locked'], name='shield_user_is_lock_ee3a3c_idx'),
        ),
        migrations.AddField(
            model_name='userbrowsersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
        migrations.AddIndex(
            model_name='userbrowsersession',
            index=models.Index(fields=['user', 'is_trusted'], name='user_browse_user_id_07f1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='userbrowsersession',
            index=models.Index(fields=['created_at'], name='user_browse_created_dfedfc_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbrowsersession',
            constraint=models.UniqueConstraint(fields=('user', 'browser_fingerprint'), name='unique_user_browser_fingerprint', violation_error_message='هذه البصمة مسجلة بالفعل لهذا المستخدم'),
        ),
    ]
