# Generated by Django 6.0.6 on 2026-06-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=255, verbose_name='البصمة الرقمية')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الجهاز')),
                ('is_verified', models.BooleanField(default=True, verbose_name='هل الجهاز موثق؟')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('last_login_at', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز مستخدم',
                'db_table': 'user_devices',
            },
        ),
    ]
