# Generated by Django 6.0.6 on 2026-06-30 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbrowsersession_remove_userdevice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم الوطني أرقام فقط (6-20 خانة).', regex='^\\d{6,20}$')], verbose_name='الرقم الوطني'),
        ),
    ]
