# Generated by Django 6.0.6 on 2026-07-08 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_validity_days', models.PositiveIntegerField(default=90, verbose_name='مدة صلاحية كلمة المرور (يوم)')),
                ('max_login_attempts', models.PositiveIntegerField(default=3, verbose_name='محاولات الدخول قبل القفل')),
                ('default_geofence_radius', models.PositiveIntegerField(default=50, verbose_name='نطاق الأمان الافتراضي (متر)')),
                ('variance_alert_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='حد إنذار العجز (%)')),
                ('enable_alerts', models.BooleanField(default=True, verbose_name='تفعيل التنبيهات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'system_settings',
            },
        ),
    ]
