# Generated by Django 6.0.6 on 2026-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر اطّلاع على الإشعارات'),
        ),
    ]
