# Generated by Django 6.0.6 on 2026-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_notifications_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audit_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر اطّلاع على سجل التدقيق'),
        ),
    ]
