# Generated by Django 6.0.6 on 2026-06-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicalFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(choices=[('valve_leak', 'تسريب في الصمامات'), ('gps_sensor', 'عطل في نظام GPS'), ('meter_fault', 'خلل في عداد التدفق'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العطل')),
                ('description', models.TextField(verbose_name='وصف العطل')),
                ('is_critical', models.BooleanField(default=False, verbose_name='هل يمنع التشغيل؟')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('fixing', 'قيد الإصلاح'), ('closed', 'تمت الصيانة')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مبلغ البلاغ')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.truck', verbose_name='الشاحنة')),
            ],
            options={
                'verbose_name': 'بلاغ عطل ميكانيكي',
                'db_table': 'shield_mechanical_faults',
            },
        ),
    ]
