# Generated by Django 6.0.6 on 2026-07-01 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_initial'),
        ('trips', '0006_alter_dischargerecord_geofence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanicalfault',
            options={'ordering': ['-created_at'], 'verbose_name': 'بلاغ عطل ميكانيكي', 'verbose_name_plural': 'بلاغات الأعطال الميكانيكية'},
        ),
        migrations.AddField(
            model_name='mechanicalfault',
            name='action_taken',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الإجراء المتخذ'),
        ),
        migrations.AddField(
            model_name='mechanicalfault',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fault_reports/%Y/%m/', verbose_name='صورة العطل'),
        ),
        migrations.AddField(
            model_name='mechanicalfault',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='trips.station', verbose_name='المحطة المرتبطة'),
        ),
        migrations.AddField(
            model_name='mechanicalfault',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='trips.trip', verbose_name='الرحلة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='mechanicalfault',
            name='fault_type',
            field=models.CharField(choices=[('valve_leak', 'تسريب في الصمامات'), ('gps_sensor', 'عطل في نظام GPS'), ('meter_fault', 'خلل في عداد التدفق'), ('reading_variance', 'فارق في القراءات الفيزيائية'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العطل'),
        ),
        migrations.AlterField(
            model_name='mechanicalfault',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_faults', to=settings.AUTH_USER_MODEL, verbose_name='مبلغ البلاغ'),
        ),
        migrations.AlterField(
            model_name='mechanicalfault',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='trips.truck', verbose_name='الشاحنة'),
        ),
    ]
