# Generated by Django 6.0.6 on 2026-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ban', 'حظر نهائي'), ('suspend', 'تجميد مؤقت'), ('unlock', 'إلغاء قفل الحساب'), ('reset_device', 'إعادة تعيين جهاز معتمد')], max_length=20)),
                ('reason', models.TextField(verbose_name='المبرر الإداري')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل الإجراء سارٍ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إجراء إداري',
                'db_table': 'shield_admin_actions',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='نوع الإجراء')),
                ('target_table', models.CharField(max_length=100, verbose_name='الجدول المستهدف')),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'db_table': 'shield_audit_logs',
            },
        ),
    ]
