# Generated by Django 6.0.6 on 2026-07-09 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'إجراء إداري'},
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('ban', 'حظر نهائي'), ('suspend', 'تجميد مؤقت'), ('unlock', 'إلغاء قفل الحساب'), ('reset_device', 'إعادة تعيين جهاز معتمد'), ('auto_lock', 'قفل تلقائي (محاولات فاشلة)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
