# Generated by Django 6.0.6 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_adminaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action_type',
            field=models.CharField(choices=[('ban', 'حظر نهائي'), ('unlock', 'إلغاء قفل الحساب'), ('auto_lock', 'قفل تلقائي (محاولات فاشلة)')], max_length=20),
        ),
    ]
