# Generated by Django 6.0.6 on 2026-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('volume_variance', 'عجز في الحجم القياسي (ASTM)'), ('geofence_violation', 'تجاوز النطاق الجغرافي (GPS)'), ('seal_tampering', 'محاولة تلاعب بختم QR'), ('unauthorized_device', 'تسجيل دخول من جهاز غير مصرح')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('critical', 'حرج')], max_length=20)),
                ('description', models.TextField(verbose_name='تفاصيل الإنذار')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت معالجة الإنذار')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إنذار أمني',
                'verbose_name_plural': 'الإنذارات الأمنية',
                'db_table': 'shield_alerts',
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_to_correct', models.CharField(max_length=50, verbose_name='الحقل المراد تعديله')),
                ('old_value', models.CharField(max_length=255, verbose_name='القيمة القديمة')),
                ('new_value', models.CharField(max_length=255, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(verbose_name='مبررات الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب تصحيح بيانات',
                'verbose_name_plural': 'طلبات تصحيح البيانات',
                'db_table': 'shield_correction_requests',
            },
        ),
    ]
