# Generated by Django 6.0.6 on 2026-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('volume_variance', 'عجز في الحجم القياسي (ASTM)'), ('geofence_violation', 'تجاوز النطاق الجغرافي (GPS)'), ('seal_tampering', 'محاولة تلاعب بختم QR'), ('unauthorized_device', 'تسجيل دخول من جهاز غير مصرح')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('critical', 'حرج')], max_length=20)),
                ('description', models.TextField(verbose_name='تفاصيل الإنذار')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إنذار',
                'verbose_name_plural': 'الإنذارات',
                'db_table': 'shield_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب طلب التصحيح')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب تصحيح',
                'verbose_name_plural': 'طلبات التصحيح',
                'db_table': 'shield_correction_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
