# Generated by Django 6.0.6 on 2026-06-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('volume_variance', 'عجز في الحجم القياسي (ASTM)'), ('geofence_violation', 'تجاوز النطاق الجغرافي (GPS)'), ('seal_tampering', 'محاولة تلاعب بختم QR'), ('unauthorized_device', 'تسجيل دخول من جهاز غير مصرح')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('critical', 'حرج')], max_length=20)),
                ('description', models.TextField(verbose_name='تفاصيل الإنذار')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_alerts', to='trips.trip')),
            ],
            options={
                'db_table': 'shield_alerts',
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_to_correct', models.CharField(max_length=50, verbose_name='الحقل المراد تعديله')),
                ('old_value', models.CharField(max_length=255, verbose_name='القيمة القديمة')),
                ('new_value', models.CharField(max_length=255, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(verbose_name='مبررات الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='trips.trip')),
            ],
            options={
                'db_table': 'shield_correction_requests',
            },
        ),
    ]
