# Generated by Django 6.0.6 on 2026-06-18 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_alerts', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL),
        ),
    ]
