# Generated by Django 6.0.6 on 2026-07-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('volume_variance', 'عجز في الحجم القياسي (ASTM)'), ('geofence_violation', 'تجاوز النطاق الجغرافي (GPS)'), ('seal_tampering', 'محاولة تلاعب بختم QR')], max_length=50),
        ),
    ]
