# Generated by Django 6.0.6 on 2026-06-18 18:00

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_volume_ambient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الحجم الظاهري المفرغ (لتر)')),
                ('discharge_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الحرارة عند التفريغ (°C)')),
                ('discharge_density', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='الكثافة عند التفريغ')),
                ('discharge_volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحجم القياسي عند 15°C')),
                ('variance_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='فارق العجز (لتر)')),
                ('variance_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='نسبة العجز (%)')),
                ('is_suspect', models.BooleanField(default=False, verbose_name='شحنة مشبوهة')),
                ('seal_check_passed', models.BooleanField(default=False, verbose_name='الأختام مطابقة؟')),
                ('seal_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الأختام')),
                ('scan_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض عند المسح')),
                ('scan_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول عند المسح')),
                ('scan_distance_m', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='المسافة عن المحطة (متر)')),
                ('geofence_status', models.CharField(choices=[('green', 'داخل النطاق الآمن (0-50م)'), ('yellow', 'نطاق تحذير (51-150م)'), ('red', 'خارج النطاق (أكثر من 150م)')], default='red', max_length=10, verbose_name='حالة النطاق الجغرافي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التفريغ')),
            ],
            options={
                'verbose_name': 'سجل تفريغ',
                'verbose_name_plural': 'سجلات التفريغ',
                'db_table': 'shield_discharge_records',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='رقم رخصة القيادة')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الزبون')),
                ('station_name', models.CharField(max_length=255, verbose_name='اسم المحطة')),
                ('company_branch', models.CharField(max_length=100, verbose_name='فرع الشركة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول')),
                ('geofence_radius', models.PositiveIntegerField(default=50, verbose_name='نطاق الأمان (متر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('is_banned', models.BooleanField(default=False, verbose_name='موقوفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محطة',
                'verbose_name_plural': 'المحطات',
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='رمز الرحلة')),
                ('fuel_type', models.CharField(default='petrol', editable=False, max_length=10, verbose_name='نوع الوقود (بنزين فقط)')),
                ('seal_numbers', models.CharField(max_length=255, verbose_name='أرقام الأختام')),
                ('shipped_volume_ambient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الحجم الظاهري المشحون (لتر)')),
                ('shipped_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الحرارة عند الشحن (°C)')),
                ('shipped_density', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='الكثافة عند الشحن')),
                ('shipped_volume_15c', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحجم القياسي عند 15°C')),
                ('qr_token', models.UUIDField(default=trips.models.generate_qr_token, unique=True, verbose_name='توكن QR')),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية QR')),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('in_transit', 'في الطريق'), ('arrived', 'وصلت المحطة'), ('completed', 'مكتملة'), ('canceled', 'ملغاة')], default='created', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'db_table': 'shield_trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعة (لتر)')),
                ('status', models.CharField(choices=[('active', 'في الخدمة'), ('maintenance', 'صيانة'), ('out_of_service', 'خارج الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('last_inspection_date', models.DateField(verbose_name='تاريخ آخر فحص')),
                ('is_gps_active', models.BooleanField(default=True, verbose_name='GPS مفعل')),
            ],
            options={
                'verbose_name': 'شاحنة',
                'verbose_name_plural': 'الشاحنات',
                'db_table': 'shield_trucks',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50, unique=True, verbose_name='رمز المستودع')),
                ('warehouse_name', models.CharField(max_length=255, verbose_name='اسم المستودع')),
                ('location_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'db_table': 'warehouses',
            },
        ),
    ]
