# Generated by Django 6.0.6 on 2026-06-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='رخصة القيادة')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الزبون')),
                ('station_name', models.CharField(max_length=255, verbose_name='اسم المحطة')),
                ('company_branch', models.CharField(max_length=100, verbose_name='الشركة التابعة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='خط الطول')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=30, unique=True, verbose_name='كود المستودع')),
                ('warehouse_name', models.CharField(max_length=255, verbose_name='اسم المستودع')),
                ('location_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50, unique=True, verbose_name='رقم اللوحة')),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعة (لتر)')),
                ('status', models.CharField(choices=[('active', 'نشطة جاهزة للعمل'), ('maintenance', 'تحت الصيانة'), ('out_of_service', 'خارج الخدمة')], default='active', max_length=20)),
                ('last_inspection_date', models.DateField(verbose_name='تاريخ آخر فحص')),
                ('is_gps_active', models.BooleanField(default=True, verbose_name='GPS مفعل؟')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.driver')),
            ],
            options={
                'db_table': 'shield_trucks',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(max_length=100, unique=True, verbose_name='رمز الرحلة')),
                ('shipped_volume_15c', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الحجم القياسي المشحون')),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('in_transit', 'في الطريق'), ('arrived', 'وصلت المحطة'), ('completed', 'مكتملة'), ('canceled', 'ملغاة')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trips', to=settings.AUTH_USER_MODEL)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_trips', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.station')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.truck')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.warehouse')),
            ],
        ),
    ]
