# Generated by Django 6.0.6 on 2026-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_volume_ambient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الحجم الفعلي المفرغ (الظاهري)')),
                ('discharge_temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درجة الحرارة عند التفريغ')),
                ('discharge_density', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الكثافة المقاسة عند التفريغ')),
                ('discharge_volume_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحجم القياسي المفرغ عند 15°C')),
                ('variance_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='فارق العجز باللتر')),
                ('is_suspect', models.BooleanField(default=False, verbose_name='شحنة مشبوهة / احتمال تهريب')),
                ('agent_scanned_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض الفعلي لحظة المسح')),
                ('agent_scanned_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول الفعلي لحظة المسح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت توثيق التفريغ')),
            ],
            options={
                'verbose_name': 'سجل تفريغ',
                'verbose_name_plural': 'سجلات التفريغ',
                'db_table': 'shield_discharge_records',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني')),
                ('driver_name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='رقم رخصة القيادة')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الزبون')),
                ('station_name', models.CharField(max_length=255, verbose_name='اسم المحطة')),
                ('company_branch', models.CharField(max_length=100, verbose_name='فرع الشركة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط العرض المرجعي')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='خط الطول المرجعي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محطة',
                'verbose_name_plural': 'المحطات',
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='رمز الرحلة الفريد')),
                ('seal_numbers', models.CharField(help_text='أدخل الأرقام مفصولة بفاصلة، مثال: 5501,5502,5503', max_length=255, verbose_name='أرقام أختام الحجرات')),
                ('shipped_volume_ambient', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحجم الفعلي المشحون (الظاهري)')),
                ('shipped_temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='درجة الحرارة عند الشحن (°C)')),
                ('shipped_density', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='الكثافة المرصودة عند الشحن')),
                ('shipped_volume_15c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحجم القياسي المشحون عند 15°C')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='صورة رمز QR')),
                ('status', models.CharField(choices=[('created', 'تم الإنشاء'), ('in_transit', 'في الطريق'), ('arrived', 'وصلت المحطة'), ('completed', 'مكتملة ومفرغة'), ('canceled', 'ملغاة')], default='created', max_length=20, verbose_name='حالة الرحلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رحلة',
                'verbose_name_plural': 'الرحلات',
                'db_table': 'shield_trips',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الشاحنة / اللوحة')),
                ('capacity_liters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعة باللتر')),
                ('status', models.CharField(choices=[('active', 'في الخدمة'), ('maintenance', 'صيانة'), ('out_of_service', 'خارج الخدمة')], default='active', max_length=20, verbose_name='حالة الشاحنة')),
                ('last_inspection_date', models.DateField(verbose_name='تاريخ آخر فحص')),
                ('is_gps_active', models.BooleanField(default=True, verbose_name='حالة جهاز الـ GPS')),
            ],
            options={
                'verbose_name': 'شاحنة',
                'verbose_name_plural': 'الشاحنات',
                'db_table': 'shield_trucks',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50, unique=True, verbose_name='رمز المستودع')),
                ('warehouse_name', models.CharField(max_length=255, verbose_name='اسم المستودع')),
                ('location_city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address_details', models.TextField(verbose_name='تفاصيل العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'db_table': 'warehouses',
            },
        ),
    ]
