# Generated by Django 6.0.6 on 2026-06-18 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargerecord',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_records', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المحطة'),
        ),
        migrations.AddField(
            model_name='station',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_stations', to=settings.AUTH_USER_MODEL, verbose_name='المندوبون المعينون'),
        ),
        migrations.AddField(
            model_name='trip',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_trips', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المحطة'),
        ),
        migrations.AddField(
            model_name='trip',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_trips', to=settings.AUTH_USER_MODEL, verbose_name='موظف المستودع'),
        ),
        migrations.AddField(
            model_name='trip',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.station', verbose_name='المحطة'),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_record', to='trips.trip', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.driver', verbose_name='السائق المعين'),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.truck', verbose_name='الشاحنة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='الموظفون المعينون'),
        ),
        migrations.AddField(
            model_name='trip',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.warehouse', verbose_name='المستودع'),
        ),
    ]
