# Generated by Django 6.0.6 on 2026-06-22 08:34

import trips.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dischargerecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل تفريغ', 'verbose_name_plural': 'سجلات التفريغ'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['driver_name'], 'verbose_name': 'سائق', 'verbose_name_plural': 'السائقين'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_name'], 'verbose_name': 'محطة', 'verbose_name_plural': 'المحطات'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['truck_id'], 'verbose_name': 'شاحنة', 'verbose_name_plural': 'الشاحنات'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['warehouse_name'], 'verbose_name': 'مستودع', 'verbose_name_plural': 'المستودعات'},
        ),
        migrations.AddField(
            model_name='trip',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت مسح QR من قبل المندوب (تسجيل الحدث الأمني)'),
        ),
        migrations.AlterField(
            model_name='dischargerecord',
            name='is_suspect',
            field=models.BooleanField(default=False, verbose_name='شحنة مشبوهة (عجز أو جيو أو أختام)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية QR (48 ساعة)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='qr_token',
            field=models.UUIDField(default=trips.models.generate_qr_token, unique=True, verbose_name='توكن QR الفريد (حماية من Enumeration)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'في الطريق'), ('completed', 'مكتملة'), ('suspect', 'مشبوهة'), ('canceled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddIndex(
            model_name='dischargerecord',
            index=models.Index(fields=['trip'], name='shield_disc_trip_id_9c3452_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargerecord',
            index=models.Index(fields=['agent'], name='shield_disc_agent_i_54fc57_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargerecord',
            index=models.Index(fields=['is_suspect'], name='shield_disc_is_susp_714529_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargerecord',
            index=models.Index(fields=['geofence_status'], name='shield_disc_geofenc_73d7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='dischargerecord',
            index=models.Index(fields=['created_at'], name='shield_disc_created_db173c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_code'], name='shield_trip_trip_co_0da3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='shield_trip_status_41aeae_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['dispatcher'], name='shield_trip_dispatc_a69b83_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['agent'], name='shield_trip_agent_i_3302ad_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['qr_scanned_at'], name='shield_trip_qr_scan_90f909_idx'),
        ),
    ]
