# Generated by Django 6.0.6 on 2026-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_dischargerecord_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargerecord',
            name='scan_distance_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المسافة عن المحطة (متر)'),
        ),
    ]
