# Generated by Django 6.0.6 on 2026-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_warehouse_latitude_warehouse_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargerecord',
            name='geofence_status',
            field=models.CharField(choices=[('green', 'داخل النطاق الآمن'), ('yellow', 'نطاق السماحية (هامش الخطأ)'), ('red', 'خارج النطاق المسموح')], default='red', max_length=10, verbose_name='حالة النطاق الجغرافي'),
        ),
    ]
