# Generated by Django 6.0.6 on 2026-07-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_dischargerecord_geofence_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'سائق', 'verbose_name_plural': 'السائقين'},
        ),
        migrations.AddField(
            model_name='driver',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='trips.warehouse', verbose_name='المستودع التابع له'),
        ),
    ]
