# Generated by Django 6.0.6 on 2026-07-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_driver_options_driver_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
    ]
