# Generated by Django 6.0.6 on 2026-07-11 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_truck_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_transit'])), fields=('truck',), name='one_active_trip_per_truck'),
        ),
    ]
